# Exploratory Data Analysis

## Analysis Objectives:

### 1. League Comparisons (Sự khác biệt giữa các leagues)
- Comparing major European leagues
- Performance metrics across different leagues
- League-specific characteristics

### 2. Statistical Metrics Analysis (Thống kê các chỉ số khác)
- Goals analysis
- Cards (Yellow/Red)
- Fouls
- Other key performance indicators

### 3. Correlation Analysis (Sự tương quan của các chỉ số được thống kê)
- Relationship between different metrics
- Impact factors analysis
- Pattern identification

### 4. Top European Scorers Analysis (Thống kê ghi bàn của các cầu thủ top Châu Âu)
- Leading goal scorers
- Performance comparison
- Scoring patterns and trends

---

In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
%matplotlib inline
sns.set_style('whitegrid')

In [12]:
player_df = pd.read_csv("football/players.csv")

player_df.head()

,player_id,first_name,last_name,name,last_season,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,...,foot,height_in_cm,contract_expiration_date,agent_name,image_url,url,current_club_domestic_competition_id,current_club_name,market_value_in_eur,highest_market_value_in_eur
0,10,Miroslav,Klose,Miroslav Klose,2015,398,miroslav-klose,Poland,Opole,Germany,...,right,184.0,NaN,ASBW Sport Marketing,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/miroslav-klose...,IT1,Società Sportiva Lazio S.p.A.,1000000.0,30000000.0
1,26,Roman,Weidenfeller,Roman Weidenfeller,2017,16,roman-weidenfeller,Germany,Diez,Germany,...,left,190.0,NaN,Neubauer 13 GmbH,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/roman-weidenfe...,L1,Borussia Dortmund,750000.0,8000000.0
2,65,Dimitar,Berbatov,Dimitar Berbatov,2015,1091,dimitar-berbatov,Bulgaria,Blagoevgrad,Bulgaria,...,NaN,NaN,NaN,CSKA-AS-23 Ltd.,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/dimitar-berbat...,GR1,Panthessalonikios Athlitikos Omilos Konstantin...,1000000.0,34500000.0
3,77,NaN,Lúcio,Lúcio,2012,506,lucio,Brazil,Brasília,Brazil,...,NaN,NaN,NaN,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/lucio/profil/s...,IT1,Juventus Football Club,200000.0,24500000.0
4,80,Tom,Starke,Tom Starke,2017,27,tom-starke,East Germany (GDR),Freital,Germany,...,right,194.0,NaN,IFM,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/tom-starke/pro...,L1,FC Bayern München,100000.0,3000000.0

In [3]:
#getting to know the data

print("shape of df:",player_df.shape)
print(player_df.columns)
print(player_df.dtypes)
print("Number of null values:\n",player_df.isnull().sum())

shape of df: (32598, 23)
Index(['player_id', 'first_name', 'last_name', 'name', 'last_season',
       'current_club_id', 'player_code', 'country_of_birth', 'city_of_birth',
       'country_of_citizenship', 'date_of_birth', 'sub_position', 'position',
       'foot', 'height_in_cm', 'contract_expiration_date', 'agent_name',
       'image_url', 'url', 'current_club_domestic_competition_id',
       'current_club_name', 'market_value_in_eur',
       'highest_market_value_in_eur'],
      dtype='object')
player_id                                 int64
first_name                               object
last_name                                object
name                                     object
last_season                               int64
current_club_id                           int64
player_code                              object
country_of_birth                         object
city_of_birth                            object
country_of_citizenship                   object
date_of_birth                            object
sub_position                             object
position                                 object
foot                                     object
height_in_cm                            float64
contract_expiration_date                 object
agent_name                               object
image_url                                object
url                                      object
current_club_domestic_competition_id     object
current_club_name                        object
market_value_in_eur                     float64
highest_market_value_in_eur             float64
dtype: object
Number of null values:
 player_id                                   0
first_name                               2061
last_name                                   0
name                                        0
last_season                                 0
current_club_id                             0
player_code                                 0
country_of_birth                         2797
city_of_birth                            2453
country_of_citizenship                    383
date_of_birth                              47
sub_position                              180
position                                    0
foot                                     2535
height_in_cm                             2257
contract_expiration_date                12093
agent_name                              16027
image_url                                   0
url                                         0
current_club_domestic_competition_id        0
current_club_name                           0
market_value_in_eur                      1520
highest_market_value_in_eur              1520
dtype: int64

### So there are somefeatures in the players table that i need to drop as it not important : 
drop first name, last name, contract_expired_date,city of birth;

In [4]:
player_df.drop(['first_name','last_name','city_of_birth','contract_expiration_date'],axis=1,inplace=True)
player_df.head()

,player_id,name,last_season,current_club_id,player_code,country_of_birth,country_of_citizenship,date_of_birth,sub_position,position,foot,height_in_cm,agent_name,image_url,url,current_club_domestic_competition_id,current_club_name,market_value_in_eur,highest_market_value_in_eur
0,10,Miroslav Klose,2015,398,miroslav-klose,Poland,Germany,1978-06-09 00:00:00,Centre-Forward,Attack,right,184.0,ASBW Sport Marketing,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/miroslav-klose...,IT1,Società Sportiva Lazio S.p.A.,1000000.0,30000000.0
1,26,Roman Weidenfeller,2017,16,roman-weidenfeller,Germany,Germany,1980-08-06 00:00:00,Goalkeeper,Goalkeeper,left,190.0,Neubauer 13 GmbH,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/roman-weidenfe...,L1,Borussia Dortmund,750000.0,8000000.0
2,65,Dimitar Berbatov,2015,1091,dimitar-berbatov,Bulgaria,Bulgaria,1981-01-30 00:00:00,Centre-Forward,Attack,NaN,NaN,CSKA-AS-23 Ltd.,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/dimitar-berbat...,GR1,Panthessalonikios Athlitikos Omilos Konstantin...,1000000.0,34500000.0
3,77,Lúcio,2012,506,lucio,Brazil,Brazil,1978-05-08 00:00:00,Centre-Back,Defender,NaN,NaN,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/lucio/profil/s...,IT1,Juventus Football Club,200000.0,24500000.0
4,80,Tom Starke,2017,27,tom-starke,East Germany (GDR),Germany,1981-03-18 00:00:00,Goalkeeper,Goalkeeper,right,194.0,IFM,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/tom-starke/pro...,L1,FC Bayern München,100000.0,3000000.0

In [5]:
transfer_df=pd.read_csv("football/transfers.csv")
print("shape of df:",transfer_df.shape)
print(transfer_df.columns)
print("Null values in transfer_df:\n",transfer_df.isnull().sum())

shape of df: (79629, 10)
Index(['player_id', 'transfer_date', 'transfer_season', 'from_club_id',
       'to_club_id', 'from_club_name', 'to_club_name', 'transfer_fee',
       'market_value_in_eur', 'player_name'],
      dtype='object')
Null values in transfer_df:
 player_id                  0
transfer_date              0
transfer_season            0
from_club_id               0
to_club_id                 0
from_club_name             0
to_club_name               0
transfer_fee           27707
market_value_in_eur    30305
player_name                0
dtype: int64

In [6]:
transfer_df.drop(['transfer_date','transfer_fee'],axis=1,inplace=True)
transfer_df.head()

,player_id,transfer_season,from_club_id,to_club_id,from_club_name,to_club_name,market_value_in_eur,player_name
0,16136,26/27,417,123,OGC Nice,Retired,500000.0,Dante
1,1138758,26/27,336,631,Sporting CP,Chelsea,45000000.0,Geovany Quenda
2,195778,25/26,79,27,VfB Stuttgart,Bayern Munich,12000000.0,Alexander Nübel
3,569033,25/26,39,27,1.FSV Mainz 05,Bayern Munich,4000000.0,Armindo Sieb
4,626913,25/26,398,380,Lazio,Salernitana,15000000.0,Boulaye Dia

In [7]:
print("Number of null values for players:\n",player_df.isnull().sum())
print("Number of null values for transfer:\n",transfer_df.isnull().sum())

Number of null values for players:
 player_id                                   0
name                                        0
last_season                                 0
current_club_id                             0
player_code                                 0
country_of_birth                         2797
country_of_citizenship                    383
date_of_birth                              47
sub_position                              180
position                                    0
foot                                     2535
height_in_cm                             2257
agent_name                              16027
image_url                                   0
url                                         0
current_club_domestic_competition_id        0
current_club_name                           0
market_value_in_eur                      1520
highest_market_value_in_eur              1520
dtype: int64
Number of null values for transfer:
 player_id                  0
transfer_season            0
from_club_id               0
to_club_id                 0
from_club_name             0
to_club_name               0
market_value_in_eur    30305
player_name                0
dtype: int64

In [8]:
test1=pd.read_csv("football/players.csv")
test2=pd.read_csv("football/transfers.csv")

In [9]:
def create_transfer_history(player_df, transfer_df):
    if player_df.empty or transfer_df.empty:
        print("Warning: Input DataFrames are empty. Returning an empty DataFrame.")
        return pd.DataFrame()

    # Merge the two DataFrames on 'player_id'
    transfer_history = pd.merge(
        transfer_df,
        player_df,
        on='player_id',
        how='left',  # Use left join to keep all transfer records
        suffixes=('_transfer', '_player')
    )


    if transfer_history.empty:
         print("Warning: No matching player_id found between the two DataFrames.")
         return pd.DataFrame()


    # Select and rename relevant columns
    transfer_history = transfer_history[[
        'player_id',
        'player_name',
        'transfer_season',
        'from_club_name',
        'to_club_name',
        'market_value_in_eur_transfer',
        'name',  # Player name from player_df
        'position',
        'country_of_birth',
        'city_of_birth',
        'country_of_citizenship'
    ]].rename(columns={
        'market_value_in_eur_transfer': 'transfer_market_value_in_eur',
        'name': 'player_name_playerdf'  #added this line to make the column name unique
    })


    return transfer_history
transfer_hist=create_transfer_history(test1, test2)
transfer_hist.head()
haaland_transfer=transfer_hist[transfer_hist['player_name'] == 'Erling Haaland']
print(haaland_transfer)

       player_id     player_name transfer_season from_club_name  \
20964     418560  Erling Haaland           22/23  Bor. Dortmund
39019     418560  Erling Haaland           19/20    RB Salzburg
45449     418560  Erling Haaland           18/19       Molde FK
55558     418560  Erling Haaland           16/17          Bryne
60772     418560  Erling Haaland           15/16  Bryne FK Yth.

        to_club_name  transfer_market_value_in_eur player_name_playerdf  \
20964       Man City                   150000000.0       Erling Haaland
39019  Bor. Dortmund                    45000000.0       Erling Haaland
45449    RB Salzburg                     5000000.0       Erling Haaland
55558       Molde FK                      200000.0       Erling Haaland
60772          Bryne                           NaN       Erling Haaland

      position country_of_birth city_of_birth country_of_citizenship
20964   Attack          England         Leeds                 Norway
39019   Attack          England         Leeds                 Norway
45449   Attack          England         Leeds                 Norway
55558   Attack          England         Leeds                 Norway
60772   Attack          England         Leeds                 Norway

In [ ]:
games_df=pd.read_csv("football/games.csv")
club_games_df=pd.read_csv("football/club_games.csv")

In [36]:
print(transfer_hist.isnull().sum())

player_id                           0
player_name                         0
transfer_season                     0
from_club_name                      0
to_club_name                        0
transfer_market_value_in_eur    30305
player_name_playerdf                0
position                            0
country_of_birth                 3187
city_of_birth                    3185
country_of_citizenship              0
dtype: int64

In [37]:
print(games_df.isnull().sum())

game_id                       0
competition_id                0
season                        0
round                         0
date                          0
home_club_id                  9
away_club_id                  9
home_club_goals              12
away_club_goals              12
home_club_position        22454
away_club_position        22455
home_club_manager_name      828
away_club_manager_name      828
stadium                     250
attendance                 9953
referee                     652
url                           0
home_club_formation        6980
away_club_formation        6811
home_club_name            12846
away_club_name            11453
aggregate                    12
competition_type              0
dtype: int64

In [38]:
# Drop columns in pandas
games_df = games_df.drop(columns=["home_club_position", "away_club_position", "aggregate", "competition_type"])

# Filter in pandas
games_df = games_df[games_df["competition_id"].isin(["CL", "FAC", "USC", "EL", "L1", "ES1","FR1","GB1","IT1"])]
print(games_df.isnull().sum())

game_id                      0
competition_id               0
season                       0
round                        0
date                         0
home_club_id                 0
away_club_id                 0
home_club_goals              0
away_club_goals              0
home_club_manager_name       6
away_club_manager_name       6
stadium                      4
attendance                2668
referee                      8
url                          0
home_club_formation       2380
away_club_formation       2376
home_club_name            2155
away_club_name            2138
dtype: int64

In [40]:

# Find rows where home_club_name is null and get their home_club_id as integers
null_home_clubs = games_df[games_df['home_club_name'].isnull()]['home_club_id'].astype(int).unique()

# Find rows where away_club_name is null and get their away_club_id as integers
null_away_clubs = games_df[games_df['away_club_name'].isnull()]['away_club_id'].astype(int).unique()

# Count original sets
print(f"Unique home club IDs with null names: {len(null_home_clubs)}")
print(f"Unique away club IDs with null names: {len(null_away_clubs)}")

# Check for intersection (IDs that appear in both lists)
intersection = np.intersect1d(null_home_clubs, null_away_clubs)
print(f"Club IDs that appear in both lists: {len(intersection)}")
if len(intersection) > 0:
    print("Intersection IDs:", intersection)

# Get union using union1d
all_null_club_ids = np.union1d(null_home_clubs, null_away_clubs)
print(f"Total unique club IDs with null names: {len(all_null_club_ids)}")

# Verify no duplicates in final result
unique_count = len(np.unique(all_null_club_ids))
print(f"After removing any duplicates: {unique_count}")

if len(all_null_club_ids) != unique_count:
    print("WARNING: There are duplicates in the union result!")
else:
    print("No duplicates found in the union result.")

Unique home club IDs with null names: 245
Unique away club IDs with null names: 245
Club IDs that appear in both lists: 220
Intersection IDs: [   14    22    26    61    62    77   119   122   144   159   164   170
   195   197   208   238   255   257   260   272   279   301   321   337
   349   352   355   358   365   409   413   419   429   452   466   496
   501   540   669   687   697   698   699   713   786   790   829   853
   899   938   941   971   972   986   988   990   991  1008  1017  1020
  1027  1028  1034  1035  1042  1045  1060  1064  1072  1074  1078  1088
  1098  1101  1109  1112  1127  1150  1180  1181  1194  1195  1198  1211
  1218  1219  1220  1252  1293  1302  1322  2156  2262  2413  2436  2454
  2455  2481  2577  2784  2790  2793  2794  2796  2797  2804  2805  2814
  2962  2963  2964  2976  3052  3053  3054  3055  3064  3137  3371  3454
  3455  3456  3489  3537  3539  3684  3688  3694  3696  3697  3698  3712
  3713  3716  3717  3721  3820  3822  3824  3825  3826  3867  3884  3933
  3936  4074  4117  4310  4441  4674  5545  5548  6028  6066  6168  6340
  6683  6684  6699  7047  7067  7123  7454  7769  8031  8123  8141  8715
  8981  9153  9527  9605  9614  9644  9829 10217 10391 10480 10586 10625
 10895 11107 11143 11177 11310 12020 12335 12469 12658 12869 13286 13499
 13556 14773 18263 20416 20786 20877 20953 21652 22010 22220 22552 22563
 22672 22687 23010 27045 29842 31367 31614 33783 34798 34860 34888 37486
 38899 46841 46842 46889]
Total unique club IDs with null names: 270
After removing any duplicates: 270
No duplicates found in the union result.

In [41]:
import requests
from bs4 import BeautifulSoup
import re
import time
import pandas as pd

def get_club_name(club_id):
    """
    Scrapes the club name from Transfermarkt using the club ID
    """
    url = f"https://www.transfermarkt.us/-/datenfakten/verein/{club_id}"
    
    # Set a user agent to avoid being blocked
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
    }
    
    try:
        # Send a request to the website
        response = requests.get(url, headers=headers)
        
        # Check if request was successful
        if response.status_code == 200:
            soup = BeautifulSoup(response.text, 'html.parser')
            
            # Find the meta tag with property="og:title"
            meta_tag = soup.find('meta', property='og:title')
            
            if meta_tag and 'content' in meta_tag.attrs:
                title_content = meta_tag['content']
                # Extract the team name (everything before " - Facts and data")
                team_name = re.sub(r' - Facts and data$', '', title_content)
                return team_name
            else:
                return None
        else:
            print(f"Failed to retrieve data for club ID {club_id}. Status code: {response.status_code}")
            return None
    except Exception as e:
        print(f"Error retrieving data for club ID {club_id}: {str(e)}")
        return None

# Create a dictionary to store the results
club_names_dict = {}

# Loop through each club ID and get its name
for club_id in all_null_club_ids:
    print(f"Processing club ID: {club_id}")
    club_name = get_club_name(club_id)
    if club_name:
        club_names_dict[club_id] = club_name
        print(f"Found: {club_id} -> {club_name}")
    else:
        print(f"Could not find name for club ID: {club_id}")
    
    # Add a small delay to avoid overwhelming the server
    time.sleep(1)

# Convert the dictionary to a DataFrame for easier handling
club_names_df = pd.DataFrame(list(club_names_dict.items()), columns=['club_id', 'club_name'])
print(f"\nSuccessfully retrieved {len(club_names_dict)} club names out of {len(all_null_club_ids)} IDs")
club_names_df.head()

Processing club ID: 14

KeyboardInterrupt:

In [42]:
# Create a copy of the dataframe to avoid modifying the original
df_filled = games_df.copy()

# Merge for home clubs
df_filled = df_filled.merge(
    club_names_df.rename(columns={'club_id': 'home_club_id', 'club_name': 'new_home_club_name'}),
    on='home_club_id',
    how='left'
)
# Only use the new name where the original is null
df_filled['home_club_name'] = df_filled['home_club_name'].fillna(df_filled['new_home_club_name'])
df_filled.drop('new_home_club_name', axis=1, inplace=True)

# Merge for away clubs
df_filled = df_filled.merge(
    club_names_df.rename(columns={'club_id': 'away_club_id', 'club_name': 'new_away_club_name'}),
    on='away_club_id',
    how='left'
)
# Only use the new name where the original is null
df_filled['away_club_name'] = df_filled['away_club_name'].fillna(df_filled['new_away_club_name'])
df_filled.drop('new_away_club_name', axis=1, inplace=True)

# Check the results
print(f"Original null home_club_name: {games_df['home_club_name'].isnull().sum()}")
print(f"Original null away_club_name: {games_df['away_club_name'].isnull().sum()}")
print(f"After filling null home_club_name: {df_filled['home_club_name'].isnull().sum()}")
print(f"After filling null away_club_name: {df_filled['away_club_name'].isnull().sum()}")

# Show sample of filled data
df_filled[['home_club_id', 'home_club_name', 'away_club_id', 'away_club_name']].sample(5)

Original null home_club_name: 2155
Original null away_club_name: 2138
After filling null home_club_name: 0
After filling null away_club_name: 0

,home_club_id,home_club_name,away_club_id,away_club_name
22512,2481.0,FC Sheriff Tiraspol,681.0,Real Sociedad de Fútbol S.A.D.
16554,3.0,1.FC Köln,38.0,Fortuna Düsseldorf
6216,39.0,1. Fußball- und Sportverein Mainz 05,16.0,Borussia Dortmund
7670,167.0,Fußball-Club Augsburg 1907,44.0,Hertha BSC
3108,405.0,Aston Villa Football Club,873.0,Crystal Palace Football Club

In [3]:
appearances_df = pd.read_csv("football/appearances.csv")
appearances_df = appearances_df[appearances_df["competition_id"].isin(["CL", "FAC", "USC", "EL", "L1", "ES1","FR1","GB1","IT1"])]

print(appearances_df.isnull().sum())

appearance_id             0
game_id                   0
player_id                 0
player_club_id            0
player_current_club_id    0
date                      0
player_name               0
competition_id            0
yellow_cards              0
red_cards                 0
goals                     0
assists                   0
minutes_played            0
dtype: int64

In [4]:
games_lineup_df = pd.read_csv("football/game_lineups.csv")
games_lineup_df = games_lineup_df[['game_id', 'player_id', 'player_name', 'type', 'position', 'number', 'team_captain']]
print(games_lineup_df.isnull().sum())

game_id         0
player_id       0
player_name     0
type            0
position        3
number          0
team_captain    0
dtype: int64

In [9]:
# First, let's check column names to confirm the right field names
print("games_lineup_df columns:", games_lineup_df.columns.tolist())
print("appearances_df columns:", appearances_df.columns.tolist())

# Merge the two DataFrames on both game_id and player_id
merged_df = pd.merge(
    appearances_df,
    games_lineup_df,
    on=["game_id", "player_id"],  # Merging on both columns
    how="inner"  # Change to "left", "right", or "outer" based on your needs
)

# Check the shape of the merged DataFrame
print(f"Original shapes: appearances_df {appearances_df.shape}, games_lineup_df {games_lineup_df.shape}")
print(f"Merged shape: {merged_df.shape}")

# Display the first few rows of the merged DataFrame
merged_df.head()

games_lineup_df columns: ['game_id', 'player_id', 'player_name', 'type', 'position', 'number', 'team_captain']
appearances_df columns: ['appearance_id', 'game_id', 'player_id', 'player_club_id', 'player_current_club_id', 'date', 'player_name', 'competition_id', 'yellow_cards', 'red_cards', 'goals', 'assists', 'minutes_played']
Original shapes: appearances_df (766148, 13), games_lineup_df (2191911, 7)
Merged shape: (606791, 18)

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,player_name_x,competition_id,yellow_cards,red_cards,goals,assists,minutes_played,player_name_y,type,position,number,team_captain
0,2321025_111455,2321025,111455,18,15,2013-08-09,Granit Xhaka,L1,0,0,0,0,90,Granit Xhaka,starting_lineup,Defensive Midfield,34,0
1,2321025_16136,2321025,16136,27,417,2013-08-09,Dante,L1,0,0,0,0,90,Dante,starting_lineup,Centre-Back,4,0
2,2321025_171209,2321025,171209,18,65,2013-08-09,Branimir Hrgota,L1,0,0,0,0,20,Branimir Hrgota,substitutes,Right Winger,31,0
3,2321025_17259,2321025,17259,27,27,2013-08-09,Manuel Neuer,L1,0,0,0,0,90,Manuel Neuer,starting_lineup,Goalkeeper,1,0
4,2321025_19819,2321025,19819,18,18,2013-08-09,Raffael,L1,0,0,0,0,90,Raffael,starting_lineup,Centre-Forward,11,0

In [10]:
merged_df = merged_df.drop(columns=["player_name_y", "player_current_club_id", "number","date","competition_id"])
print(merged_df.head())

    appearance_id  game_id  player_id  player_club_id    player_name_x  \
0  2321025_111455  2321025     111455              18     Granit Xhaka
1   2321025_16136  2321025      16136              27            Dante
2  2321025_171209  2321025     171209              18  Branimir Hrgota
3   2321025_17259  2321025      17259              27     Manuel Neuer
4   2321025_19819  2321025      19819              18          Raffael

   yellow_cards  red_cards  goals  assists  minutes_played             type  \
0             0          0      0        0              90  starting_lineup
1             0          0      0        0              90  starting_lineup
2             0          0      0        0              20      substitutes
3             0          0      0        0              90  starting_lineup
4             0          0      0        0              90  starting_lineup

             position  team_captain
0  Defensive Midfield             0
1         Centre-Back             0
2        Right Winger             0
3          Goalkeeper             0
4      Centre-Forward             0

In [36]:
player_df = pd.read_csv("football/players.csv")
player_df=player_df[["player_id",
  "name",
  "current_club_id",
  "country_of_birth",
  "city_of_birth",
  "date_of_birth",
  "position",
  "foot",
  "height_in_cm",
  "image_url",
  "current_club_name",
  "market_value_in_eur",
  "highest_market_value_in_eur"]]
player_df.isnull().sum()

player_id                         0
name                              0
current_club_id                   0
country_of_birth               2797
city_of_birth                  2453
date_of_birth                    47
position                          0
foot                           2535
height_in_cm                   2257
image_url                         0
current_club_name                 0
market_value_in_eur            1520
highest_market_value_in_eur    1520
dtype: int64

In [37]:
player_df['hometown']=player_df['city_of_birth'] + ", " + player_df['country_of_birth']
player_df.drop(['city_of_birth','country_of_birth'],axis=1,inplace=True)
player_df.isnull().sum()

player_id                         0
name                              0
current_club_id                   0
date_of_birth                    47
position                          0
foot                           2535
height_in_cm                   2257
image_url                         0
current_club_name                 0
market_value_in_eur            1520
highest_market_value_in_eur    1520
hometown                       2797
dtype: int64

In [40]:
player_df.count()

player_id                      32598
name                           32598
current_club_id                32598
date_of_birth                  32551
position                       32598
foot                           30063
height_in_cm                   30341
image_url                      32598
current_club_name              32598
market_value_in_eur            31078
highest_market_value_in_eur    31078
hometown                       29801
dtype: int64